import type { SeedMaterial } from './seed-schema.js';

const IMG = (seed: string, w = 1200) => `https://picsum.photos/seed/${seed}/${w}/675`;
const FILE = (name: string) => `https://files.hackathon-backend.makonew.com/content/${name}`;

export const SEED_MATERIALS_EXTRA: SeedMaterial[] = [
  {
    slug: 'bank-czasu-dla-seniorow',
    title: 'Bank czasu dla seniorów',
    excerpt: 'Innowacja społeczna polegająca na wymianie usług i wzajemnym wsparciu sąsiedzkim.',
    body: '<p>Bank czasu łączy seniorów, którzy oferują swoje umiejętności i czas w zamian za pomoc w codziennych sprawach.</p><p>W ciągu roku uczestnicy wymienili ponad 4 000 godzin wsparcia.</p>',
    type: 'innovation',
    format: 'article',
    categorySlug: 'gotowe-innowacje',
    topicSlugs: ['seniorzy', 'wolontariat'],
    tags: ['Bank czasu', 'Seniorzy'],
    cover: IMG('bank-czasu-dla-seniorow'),
    author: 'Stowarzyszenie Razem Łatwiej',
    region: 'Małopolska',
    publishedAt: '2023-06-15T00:00:00.000Z',
  },
  {
    slug: 'mobilny-punkt-wsparcia-psychicznego',
    title: 'Mobilny punkt wsparcia psychicznego',
    excerpt: 'Obwoźny punkt konsultacji psychologicznych docierający do małych miejscowości.',
    body: '<p>Zespół psychologów i psychoterapeutów odwiedza gminy, w których nie ma stałej poradni.</p>',
    type: 'innovation',
    format: 'article',
    categorySlug: 'gotowe-innowacje',
    topicSlugs: ['zdrowie-psychiczne', 'mlodziez'],
    tags: ['Wsparcie', 'Młodzież'],
    cover: IMG('mobilny-punkt-wsparcia-psychicznego'),
    author: 'Fundacja Otwarte Drzwi',
    region: 'Polska',
    isFeatured: true,
    publishedAt: '2023-07-02T00:00:00.000Z',
  },
  {
    slug: 'raport-wykluczenie-cyfrowe-seniorow',
    title: 'Raport: wykluczenie cyfrowe seniorów',
    excerpt: 'Diagnoza barier i rekomendacje włączania osób starszych w świat cyfrowy.',
    type: 'report',
    format: 'pdf',
    categorySlug: 'raporty-i-publikacje',
    topicSlugs: ['wykluczenie-cyfrowe', 'seniorzy'],
    tags: ['Raport', 'Seniorzy'],
    cover: IMG('raport-wykluczenie-cyfrowe-seniorow'),
    file: FILE('raport-wykluczenie-cyfrowe-seniorow.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 1835000,
    pages: 56,
    author: 'Instytut Polityki Cyfrowej',
    region: 'Polska',
    isFeatured: true,
    publishedAt: '2023-08-11T00:00:00.000Z',
  },
  {
    slug: 'raport-zdrowie-psychiczne-mlodziezy-regiony',
    title: 'Raport: zdrowie psychiczne młodzieży w regionach',
    excerpt: 'Analiza dostępności wsparcia psychologicznego dla młodzieży w mniejszych ośrodkach.',
    type: 'report',
    format: 'pdf',
    categorySlug: 'raporty-i-publikacje',
    topicSlugs: ['zdrowie-psychiczne', 'mlodziez'],
    tags: ['Raport', 'Młodzież'],
    cover: IMG('raport-zdrowie-psychiczne-mlodziezy-regiony'),
    file: FILE('raport-zdrowie-psychiczne-mlodziezy-regiony.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 2411000,
    pages: 84,
    author: 'Fundacja Młode Głowy',
    region: 'Małopolska',
    publishedAt: '2023-09-19T00:00:00.000Z',
  },
  {
    slug: 'publikacja-niepelnosprawnosc-rynek-pracy',
    title: 'Niepełnosprawność a rynek pracy',
    excerpt: 'Publikacja o barierach i dobrych praktykach zatrudniania osób z niepełnosprawnościami.',
    type: 'publication',
    format: 'pdf',
    categorySlug: 'raporty-i-publikacje',
    topicSlugs: ['niepelnosprawnosc', 'wolontariat'],
    tags: ['Praca', 'Niepełnosprawność'],
    cover: IMG('publikacja-niepelnosprawnosc-rynek-pracy'),
    file: FILE('publikacja-niepelnosprawnosc-rynek-pracy.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 1274000,
    pages: 44,
    author: 'Centrum Integracji Zawodowej',
    region: 'Polska',
    publishedAt: '2023-10-05T00:00:00.000Z',
  },
  {
    slug: 'poradnik-dostepne-dokumenty-ngo',
    title: 'Poradnik: dostępne dokumenty w NGO',
    excerpt: 'Jak tworzyć czytelne i dostępne dokumenty dla wszystkich odbiorców.',
    body: '<p>Poradnik omawia strukturę nagłówków, kontrasty, teksty alternatywne i oznaczanie języka w plikach.</p>',
    type: 'guide',
    format: 'pdf',
    categorySlug: 'ucz-sie-i-dzialaj',
    topicSlugs: ['niepelnosprawnosc', 'wykluczenie-cyfrowe'],
    tags: ['Dostępność', 'Dokumenty'],
    cover: IMG('poradnik-dostepne-dokumenty-ngo'),
    file: FILE('poradnik-dostepne-dokumenty-ngo.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 692000,
    pages: 28,
    author: 'Fundacja Dostępność Plus',
    publishedAt: '2023-08-22T00:00:00.000Z',
  },
  {
    slug: 'przewodnik-wolontariat-mlodziezy',
    title: 'Przewodnik: wolontariat młodzieży',
    excerpt: 'Przewodnik dla organizacji, które chcą angażować młodych wolontariuszy.',
    type: 'guide',
    format: 'pdf',
    categorySlug: 'ucz-sie-i-dzialaj',
    topicSlugs: ['wolontariat', 'mlodziez'],
    tags: ['Wolontariat', 'Młodzież'],
    cover: IMG('przewodnik-wolontariat-mlodziezy'),
    file: FILE('przewodnik-wolontariat-mlodziezy.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 812000,
    pages: 36,
    author: 'Centrum Wolontariatu',
    region: 'Kraków',
    publishedAt: '2023-11-14T00:00:00.000Z',
  },
  {
    slug: 'checklist-dostepne-wydarzenie-online',
    title: 'Lista kontrolna: dostępne wydarzenie online',
    excerpt: 'Praktyczna lista kontrolna przed organizacją dostępnego spotkania online.',
    body: '<p>Sprawdź napisy, tłumaczenie na PJM, opisy slajdów i alternatywne kanały zadawania pytań.</p>',
    type: 'checklist',
    format: 'pdf',
    categorySlug: 'ucz-sie-i-dzialaj',
    topicSlugs: ['niepelnosprawnosc', 'wykluczenie-cyfrowe'],
    tags: ['Dostępność', 'Online'],
    cover: IMG('checklist-dostepne-wydarzenie-online'),
    file: FILE('checklist-dostepne-wydarzenie-online.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 298000,
    author: 'Fundacja Dostępność Plus',
    isFeatured: true,
    publishedAt: '2023-12-01T00:00:00.000Z',
  },
  {
    slug: 'checklist-pierwszy-kontakt-senior',
    title: 'Lista kontrolna: pierwszy kontakt z seniorem',
    excerpt: 'Zestaw pytań i zasad wspierających bezpieczny pierwszy kontakt z osobą starszą.',
    type: 'checklist',
    format: 'pdf',
    categorySlug: 'ucz-sie-i-dzialaj',
    topicSlugs: ['seniorzy', 'wykluczenie-cyfrowe'],
    tags: ['Seniorzy', 'Wsparcie'],
    cover: IMG('checklist-pierwszy-kontakt-senior'),
    file: FILE('checklist-pierwszy-kontakt-senior.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 345000,
    author: 'Caritas Małopolska',
    region: 'Małopolska',
    publishedAt: '2023-06-28T00:00:00.000Z',
  },
  {
    slug: 'webinar-wykluczenie-cyfrowe-w-praktyce',
    title: 'Webinar: wykluczenie cyfrowe w praktyce',
    excerpt: 'Nagranie spotkania o realnych barierach cyfrowych seniorów i sposobach ich pokonywania.',
    type: 'webinar',
    format: 'video',
    categorySlug: 'webinary',
    topicSlugs: ['wykluczenie-cyfrowe', 'seniorzy'],
    tags: ['Webinar', 'Cyfryzacja'],
    cover: IMG('webinar-wykluczenie-cyfrowe-w-praktyce'),
    videoUrl: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    durationSeconds: 3300,
    author: 'Akademia NGO',
    publishedAt: '2023-09-07T00:00:00.000Z',
  },
  {
    slug: 'webinar-wolontariat-w-ngo',
    title: 'Webinar: wolontariat w organizacji pozarządowej',
    excerpt: 'Nagranie szkolenia o rekrutacji, motywowaniu i utrzymaniu wolontariuszy.',
    type: 'webinar',
    format: 'video',
    categorySlug: 'webinary',
    topicSlugs: ['wolontariat'],
    tags: ['Webinar', 'Wolontariat'],
    cover: IMG('webinar-wolontariat-w-ngo'),
    videoUrl: 'https://vimeo.com/148751763',
    durationSeconds: 2880,
    author: 'Akademia NGO',
    publishedAt: '2024-01-16T00:00:00.000Z',
  },
  {
    slug: 'wideo-mlodziez-zdrowie-psychiczne',
    title: 'Wideo: młodzież i zdrowie psychiczne',
    excerpt: 'Krótki film o codziennych wyzwaniach psychicznych młodych ludzi.',
    type: 'video',
    format: 'video',
    categorySlug: 'dobra-praktyka',
    topicSlugs: ['mlodziez', 'zdrowie-psychiczne'],
    tags: ['Wideo', 'Młodzież'],
    cover: IMG('wideo-mlodziez-zdrowie-psychiczne'),
    videoUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    durationSeconds: 1080,
    author: 'Fundacja Młode Głowy',
    publishedAt: '2023-10-24T00:00:00.000Z',
  },
  {
    slug: 'wideo-dostepna-praca-niepelnosprawnosc',
    title: 'Wideo: dostępna praca bez barier',
    excerpt: 'Film o dobrych praktykach zatrudniania osób z niepełnosprawnościami.',
    type: 'video',
    format: 'video',
    categorySlug: 'gotowe-innowacje',
    topicSlugs: ['niepelnosprawnosc'],
    tags: ['Wideo', 'Praca'],
    cover: IMG('wideo-dostepna-praca-niepelnosprawnosc'),
    videoUrl: 'https://vimeo.com/1084537',
    durationSeconds: 1500,
    author: 'Centrum Integracji Zawodowej',
    publishedAt: '2024-02-08T00:00:00.000Z',
  },
  {
    slug: 'mapa-wyzwan-wykluczenie-cyfrowe-gminy',
    title: 'Mapa wyzwań: wykluczenie cyfrowe w gminach',
    excerpt: 'Diagnoza lokalnych wyzwań związanych z dostępem do usług cyfrowych.',
    type: 'challenge_map',
    format: 'map',
    categorySlug: 'mapy-wyzwan',
    topicSlugs: ['wykluczenie-cyfrowe', 'seniorzy'],
    tags: ['Diagnoza', 'Cyfryzacja'],
    cover: IMG('mapa-wyzwan-wykluczenie-cyfrowe-gminy'),
    author: 'Obserwatorium Miejskie',
    region: 'Małopolska',
    publishedAt: '2023-07-19T00:00:00.000Z',
  },
  {
    slug: 'mapa-wyzwan-zdrowie-psychiczne-mlodziezy',
    title: 'Mapa wyzwań: zdrowie psychiczne młodzieży',
    excerpt: 'Diagnoza potrzeb wsparcia psychicznego młodzieży w miastach i gminach.',
    type: 'challenge_map',
    format: 'map',
    categorySlug: 'mapy-wyzwan',
    topicSlugs: ['zdrowie-psychiczne', 'mlodziez'],
    tags: ['Diagnoza', 'Młodzież'],
    cover: IMG('mapa-wyzwan-zdrowie-psychiczne-mlodziezy'),
    author: 'Obserwatorium Miejskie',
    region: 'Kraków',
    isFeatured: true,
    publishedAt: '2024-02-27T00:00:00.000Z',
  },
  {
    slug: 'case-study-wolontariat-sasiedzki',
    title: 'Studium przypadku: wolontariat sąsiedzki',
    excerpt: 'Historia programu sąsiedzkiej pomocy łączącej seniorów i wolontariuszy.',
    body: '<p>Program opierał się na mapowaniu potrzeb i łączeniu ich z lokalnymi wolontariuszami.</p><p>Po dwóch latach objął 9 dzielnic i ponad 300 osób.</p>',
    type: 'case_study',
    format: 'article',
    categorySlug: 'dobra-praktyka',
    topicSlugs: ['wolontariat', 'seniorzy'],
    tags: ['Sąsiedzi', 'Wolontariat'],
    cover: IMG('case-study-wolontariat-sasiedzki'),
    author: 'Fundacja Dobra Energia',
    region: 'Małopolska',
    publishedAt: '2023-11-29T00:00:00.000Z',
  },
  {
    slug: 'case-study-dostepna-biblioteka',
    title: 'Studium przypadku: dostępna biblioteka',
    excerpt: 'Historia modernizacji biblioteki miejskiej pod kątem dostępności.',
    body: '<p>Biblioteka wprowadziła windy, pętle indukcyjne, książki w wersji łatwej do czytania i szkolenia dla personelu.</p>',
    type: 'case_study',
    format: 'article',
    categorySlug: 'dobra-praktyka',
    topicSlugs: ['niepelnosprawnosc'],
    tags: ['Biblioteka', 'Dostępność'],
    cover: IMG('case-study-dostepna-biblioteka'),
    author: 'Miejska Biblioteka Publiczna',
    region: 'Kraków',
    publishedAt: '2024-01-09T00:00:00.000Z',
    gallery: [IMG('case-study-dostepna-biblioteka-1'), IMG('case-study-dostepna-biblioteka-2')],
  },
  {
    slug: 'publikacja-dobre-praktyki-wlaczania',
    title: 'Dobre praktyki włączania społecznego',
    excerpt: 'Zbiór sprawdzonych praktyk włączania grup zagrożonych wykluczeniem.',
    type: 'publication',
    format: 'pdf',
    categorySlug: 'raporty-i-publikacje',
    topicSlugs: ['mlodziez', 'niepelnosprawnosc', 'wolontariat'],
    tags: ['Włączanie', 'Dobre praktyki'],
    cover: IMG('publikacja-dobre-praktyki-wlaczania'),
    file: FILE('publikacja-dobre-praktyki-wlaczania.pdf'),
    fileType: 'pdf',
    fileSizeBytes: 1560000,
    pages: 60,
    author: 'Instytut Badań Społecznych',
    region: 'Polska',
    isFeatured: true,
    publishedAt: '2024-03-18T00:00:00.000Z',
  },
];
