/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matchmaking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret a problem and return ranked innovations
         * @description Interprets the problem, retrieves catalogue candidates and returns up to five grounded recommendations. Returns `needs_clarification` with up to three questions when material information is missing, `no_match` when nothing fits, and `degraded` when part of the AI pipeline is unavailable.
         */
        post: operations["createMatchmakingRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/innovations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List and search catalogue innovations
         * @description Returns a paginated list of catalogue innovations for the knowledge library. Filter by free text (`q`), problem tag, target group, evidence status and synthesis flag.
         */
        get: operations["listInnovations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/innovations/{innovationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get innovation details and source references */
        get: operations["getInnovation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List innovation tests open to testers */
        get: operations["listInnovationTests"];
        put?: never;
        /** Create an innovation test (operator) */
        post: operations["createInnovationTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get test details, application count and remaining slots */
        get: operations["getInnovationTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tests/{testId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Declare willingness to take part in a test
         * @description Registers the caller (Bearer token) or the shared demo user when no token is provided. One application per test and user.
         */
        post: operations["applyForInnovationTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tester/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my test applications with their feedback */
        get: operations["listMyTestApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tester/applications/{applicationId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit or update test feedback, rating and improvement suggestions */
        post: operations["submitTesterFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/innovations/{innovationId}/tester-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated tester ratings and improvement suggestions for an innovation */
        get: operations["getInnovationTesterFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problem-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reported social problems with their review status */
        get: operations["listProblemReports"];
        put?: never;
        /** Report a local social problem (residents, NGOs, institutions) */
        post: operations["createProblemReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problem-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single problem report and its review status */
        get: operations["getProblemReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the review status / response (administrator) */
        patch: operations["updateProblemReport"];
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard statistics for administrators
         * @description Aggregated counters for users, catalogue innovations, innovation submissions, problem reports, tests, tester applications and matchmaking, plus 14-day activity, category breakdown and recent items. `pending` submissions are those not yet accepted.
         */
        get: operations["getAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List innovation submissions for review
         * @description Paginated innovation submissions with the author. Filter by free text (`q`, matched against title, description and author e-mail), acceptance flag and workflow status. `counts` are computed over all submissions and are not affected by the filters.
         */
        get: operations["listAdminSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Accept or reject an innovation submission
         * @description Updates only `isAccepted` and/or `status`; at least one field is required. The expected review actions are `{ "isAccepted": true, "status": "approved" }` and `{ "isAccepted": false, "status": "rejected" }`.
         */
        patch: operations["updateAdminSubmission"];
        trace?: never;
    };
    "/api/v1/matchmaking/{requestId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record usefulness feedback for a recommendation */
        post: operations["submitMatchmakingFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message and receive the next assistant step
         * @description Send free text (omit `conversationId` to start a new conversation) or answer a clarification question. Depending on the updated conversation state the response is `clarification`, `recommendations` (a first page of a stable search), `no_solution` (nothing matches; offers to submit a new idea) or `message`.
         */
        post: operations["sendAssistantMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/searches/{searchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a page of a stored search ranking
         * @description Returns a slice of the stable ranking saved for a search. Does not call the LLM, generate an embedding or run vector search again.
         */
        get: operations["getAssistantSearchPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserType: "resident" | "ngo" | "local_government" | "institution";
        LocationInput: {
            municipality?: string;
            county?: string;
        };
        ConstraintsInput: {
            budgetPln?: number;
            timeframeWeeks?: number;
            availableResources?: string[];
            accessibilityNeeds?: string[];
        };
        ClarificationAnswer: {
            questionId: string;
            answer: string;
        };
        MatchmakingRequest: {
            problemDescription: string;
            userType: components["schemas"]["UserType"];
            location?: components["schemas"]["LocationInput"];
            targetGroups?: string[];
            constraints?: components["schemas"]["ConstraintsInput"];
            clarificationAnswers?: components["schemas"]["ClarificationAnswer"][];
        };
        ClarifyingQuestion: {
            id: string;
            question: string;
        };
        Citation: {
            sourceId: string;
            title: string;
            /** Format: uri */
            url?: string;
            page?: number;
            excerpt: string;
        };
        Match: {
            innovationId: string;
            title: string;
            summary: string;
            /** @enum {string} */
            relevance: "high" | "medium" | "low";
            whyItMatches: string[];
            limitations: string[];
            suggestedNextSteps: string[];
            /** @enum {string} */
            evidenceStatus: "documented" | "partially_documented" | "synthetic";
            citations: components["schemas"]["Citation"][];
        };
        RelatedEvidence: {
            id: string;
            sourceId: string;
            title: string;
            kind: string;
            summary: string;
            /** Format: uri */
            url?: string;
            synthetic: boolean;
        };
        MatchmakingResponse: {
            requestId: string;
            /** @enum {string} */
            status: "matched" | "needs_clarification" | "no_match" | "degraded";
            /** @enum {string} */
            mode: "live" | "demo";
            problemSummary: string;
            identifiedNeeds: string[];
            clarifyingQuestions: components["schemas"]["ClarifyingQuestion"][];
            matches: components["schemas"]["Match"][];
            relatedEvidence: components["schemas"]["RelatedEvidence"][];
            warnings: string[];
        };
        FeedbackRequest: {
            innovationId: string;
            useful: boolean;
            /** @enum {string} */
            reason?: "not_relevant" | "target_group_mismatch" | "constraints_mismatch" | "insufficient_evidence" | "already_known" | "other";
            comment?: string;
        };
        FeedbackResponse: {
            feedbackId: string;
            requestId: string;
            innovationId: string;
            /** @enum {boolean} */
            recorded: true;
            message: string;
        };
        SourceSummary: {
            sourceId: string;
            title: string;
            /** Format: uri */
            url?: string;
            urlVerified: boolean;
            kind: string;
            synthetic: boolean;
        };
        /** @enum {string} */
        EvidenceStatus: "documented" | "partially_documented" | "synthetic";
        InnovationSummary: {
            innovationId: string;
            title: string;
            summary: string;
            sourceId: string;
            evidenceStatus: components["schemas"]["EvidenceStatus"];
            synthetic: boolean;
            problemTags: string[];
            targetGroups: string[];
            testedIn: string[];
            applicableContexts: string[];
            estimatedCostPln: number | null;
            timeframeWeeks: number | null;
        };
        InnovationListResponse: {
            /** @description Total records after filtering. */
            total: number;
            /** @description Records in this page. */
            count: number;
            limit: number;
            offset: number;
            /** @enum {string} */
            mode: "live" | "demo";
            data: components["schemas"]["InnovationSummary"][];
            warnings: string[];
        };
        InnovationDetail: {
            innovationId: string;
            title: string;
            summary: string;
            description: string;
            /** @enum {string} */
            evidenceStatus: "documented" | "partially_documented" | "synthetic";
            synthetic: boolean;
            source: components["schemas"]["SourceSummary"];
            problemTags: string[];
            targetGroups: string[];
            testedIn: string[];
            applicableContexts: string[];
            prerequisites: string[];
            resourcesRequired: string[];
            estimatedCostPln: number | null;
            timeframeWeeks: number | null;
            citations: components["schemas"]["Citation"][];
            disclaimer: string;
        };
        /** @enum {string} */
        TestStatus: "recruiting" | "active" | "completed" | "cancelled";
        /** @enum {string} */
        TestApplicationStatus: "pending" | "accepted" | "rejected" | "withdrawn" | "completed";
        InnovationTest: {
            id: number;
            innovationId: string;
            title: string;
            description?: string | null;
            instructions?: string | null;
            location?: string | null;
            maxTesters?: number | null;
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            endAt?: string | null;
            status: components["schemas"]["TestStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
            innovationTitle?: string | null;
            innovationSummary?: string | null;
            applicationsCount?: number;
            acceptedCount?: number;
            slotsLeft?: number | null;
        };
        TestListResponse: {
            total: number;
            count: number;
            limit: number;
            offset: number;
            data: components["schemas"]["InnovationTest"][];
        };
        CreateTestRequest: {
            innovationId: string;
            title: string;
            description?: string;
            instructions?: string;
            location?: string;
            maxTesters?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            status?: components["schemas"]["TestStatus"];
        };
        TestApplicationRequest: {
            motivation?: string;
        };
        TestApplication: {
            id: number;
            testId: number;
            userId?: number;
            motivation?: string | null;
            status: components["schemas"]["TestApplicationStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MyTestApplication: components["schemas"]["TestApplication"] & {
            test?: components["schemas"]["InnovationTest"];
            feedback?: components["schemas"]["TesterFeedback"] | null;
        };
        TesterFeedbackRequest: {
            overallRating: number;
            usefulnessRating?: number;
            easeOfUseRating?: number;
            wouldUseAgain?: boolean;
            whatWorked?: string;
            problems?: string;
            suggestions?: string;
            comment?: string;
            answers?: {
                [key: string]: unknown;
            };
        };
        TesterFeedback: {
            id: number;
            applicationId: number;
            overallRating: number;
            usefulnessRating?: number | null;
            easeOfUseRating?: number | null;
            wouldUseAgain?: boolean | null;
            whatWorked?: string | null;
            problems?: string | null;
            suggestions?: string | null;
            comment?: string | null;
            answers?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TesterFeedbackEnvelope: {
            message: string;
            data: components["schemas"]["TesterFeedback"];
        };
        TesterFeedbackAggregate: {
            innovationId: string;
            applicationCount: number;
            feedbackCount: number;
            averages: {
                overall: number | null;
                usefulness: number | null;
                easeOfUse: number | null;
            };
            wouldUseAgainRatio: number | null;
            data: components["schemas"]["TesterFeedback"][];
        };
        /**
         * @description `conflict` means an explicit mismatch (never returned to the client as a recommendation).
         * @enum {string}
         */
        EligibilityStatus: "eligible" | "unknown" | "conflict";
        TextMessageInput: {
            /** @constant */
            type: "text";
            text: string;
        };
        ClarificationAnswerInput: {
            /** @constant */
            type: "clarification_answer";
            questionId: string;
            selectedOptionIds: string[];
            additionalText?: string;
        };
        AssistantMessageInput: components["schemas"]["TextMessageInput"] | components["schemas"]["ClarificationAnswerInput"];
        SendAssistantMessageRequest: {
            /** @description Omit on the first message to start a new conversation. */
            conversationId?: string;
            message: components["schemas"]["AssistantMessageInput"];
        };
        ClarificationOption: {
            id: string;
            label: string;
        };
        Clarification: {
            id: string;
            question: string;
            /** @enum {string} */
            selectionMode: "single" | "multiple";
            options: components["schemas"]["ClarificationOption"][];
            allowAdditionalText: boolean;
        };
        ClarificationResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "clarification";
            conversationId: string;
            assistantMessage: string;
            clarification: components["schemas"]["Clarification"];
        };
        RecommendationDetail: {
            label: string;
            value: string;
        };
        Recommendation: {
            id: string;
            title: string;
            summary: string;
            matchExplanation: string;
            eligibilityStatus: components["schemas"]["EligibilityStatus"];
            eligibilityDescription?: string;
            details: components["schemas"]["RecommendationDetail"][];
            url?: string;
        };
        Pagination: {
            page: number;
            pageSize: number;
            totalResults: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
        RecommendationsResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "recommendations";
            conversationId: string;
            assistantMessage: string;
            search: {
                id: string;
                recommendations: components["schemas"]["Recommendation"][];
                pagination: components["schemas"]["Pagination"];
            };
        };
        AssistantMessageResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message";
            conversationId: string;
            assistantMessage: string;
        };
        NoSolutionResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "no_solution";
            conversationId: string;
            assistantMessage: string;
            action: {
                label: string;
                href: string;
            };
        };
        SendAssistantMessageResponse: components["schemas"]["ClarificationResponse"] | components["schemas"]["RecommendationsResponse"] | components["schemas"]["NoSolutionResponse"] | components["schemas"]["AssistantMessageResponse"];
        SearchPageResponse: {
            searchId: string;
            recommendations: components["schemas"]["Recommendation"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @enum {string} */
        ProblemReportStatus: "new" | "in_review" | "planned" | "resolved" | "rejected";
        /** @enum {string} */
        ProblemReportReporter: "resident" | "ngo" | "local_government" | "institution" | "other";
        ProblemReport: {
            id: number;
            title: string;
            description: string;
            category?: string | null;
            municipality?: string | null;
            county?: string | null;
            reporterType: components["schemas"]["ProblemReportReporter"];
            status: components["schemas"]["ProblemReportStatus"];
            adminResponse?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProblemReportRequest: {
            title: string;
            description: string;
            category?: string;
            municipality?: string;
            county?: string;
            reporterType?: components["schemas"]["ProblemReportReporter"];
            /** Format: email */
            contactEmail?: string;
        };
        ProblemReportUpdateRequest: {
            status?: components["schemas"]["ProblemReportStatus"];
            adminResponse?: string;
        };
        ProblemReportListResponse: {
            total: number;
            count: number;
            limit: number;
            offset: number;
            data: components["schemas"]["ProblemReport"][];
        };
        /** @enum {string} */
        InnovationStatus: "draft" | "completed" | "submitted" | "approved" | "rejected";
        AdminSubmission: {
            id: number;
            title: string;
            description?: string | null;
            status: components["schemas"]["InnovationStatus"];
            isAccepted: boolean;
            currentStep: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            authorEmail: string | null;
            authorName: string | null;
        };
        AdminSubmissionUpdateRequest: {
            /** @description Administrator decision flag. `true` accepts the submission. */
            isAccepted?: boolean;
            status?: components["schemas"]["InnovationStatus"];
        } | unknown | unknown;
        AdminSubmissionListResponse: {
            /** @description Total records after filtering. */
            total: number;
            /** @description Records in this page. */
            count: number;
            limit: number;
            offset: number;
            /** @description Global counters over all submissions, independent of the filters. */
            counts: {
                /** @description Submissions with `isAccepted = false`. */
                pending: number;
                /** @description Submissions with `isAccepted = true`. */
                accepted: number;
                /** @description Submissions with `status = 'rejected'`. */
                rejected: number;
            };
            data: components["schemas"]["AdminSubmission"][];
        };
        AdminStats: {
            /** Format: date-time */
            generatedAt: string;
            users: {
                total: number;
                newThisWeek: number;
            };
            innovations: {
                /** @description Catalogue innovations (not submissions). */
                catalogue: number;
            };
            submissions: {
                total: number;
                pending: number;
                accepted: number;
                rejected: number;
                newThisWeek: number;
            };
            problemReports: {
                total: number;
                new: number;
                inReview: number;
                planned: number;
                resolved: number;
                rejected: number;
                newThisWeek: number;
            };
            tests: {
                total: number;
                recruiting: number;
                active: number;
            };
            testerApplications: {
                total: number;
                pending: number;
            };
            matchmaking: {
                requests: number;
                feedback: number;
            };
            /** @description Top problem report categories; missing category counts as `Inne`. */
            categories: {
                category: string;
                count: number;
            }[];
            /** @description Last 14 days, inclusive, chronological; missing days are filled with zeros. */
            activityByDay: {
                date: string;
                submissions: number;
                reports: number;
            }[];
            recentSubmissions: {
                id: number;
                title: string;
                status: components["schemas"]["InnovationStatus"];
                isAccepted: boolean;
                /** Format: date-time */
                createdAt: string;
                authorEmail: string | null;
            }[];
            recentReports: {
                id: number;
                title: string;
                status: components["schemas"]["ProblemReportStatus"];
                category: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
            /** @description Merged submissions, problem reports, tester applications and tests, newest first. */
            recentActivity: {
                /** @enum {string} */
                type: "submission" | "report" | "application" | "test";
                title: string;
                /** Format: date-time */
                at: string;
                status: string;
            }[];
        };
        ErrorEnvelope: {
            error: {
                code: string;
                /** @description Safe Polish message. */
                message: string;
                requestId: string;
                retryable: boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createMatchmakingRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchmakingRequest"];
            };
        };
        responses: {
            /** @description Matchmaking result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchmakingResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listInnovations: {
        parameters: {
            query?: {
                /** @description Free-text search over title, summary, description and tags. */
                q?: string;
                /** @description Exact problem tag match (diacritic-insensitive, case-insensitive). */
                problemTag?: string;
                /** @description Exact target group match (diacritic-insensitive, case-insensitive). */
                targetGroup?: string;
                evidenceStatus?: components["schemas"]["EvidenceStatus"];
                /** @description When set, only synthetic (true) or verified (false) records are returned. */
                synthetic?: boolean;
                sort?: "title" | "cost" | "timeframe";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated innovation list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InnovationListResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getInnovation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                innovationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Innovation detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InnovationDetail"];
                };
            };
            /** @description Innovation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listInnovationTests: {
        parameters: {
            query?: {
                status?: components["schemas"]["TestStatus"];
                innovationId?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of innovation tests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestListResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createInnovationTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestRequest"];
            };
        };
        responses: {
            /** @description Test created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: components["schemas"]["InnovationTest"];
                    };
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getInnovationTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InnovationTest"];
                    };
                };
            };
            /** @description Test not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    applyForInnovationTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TestApplicationRequest"];
            };
        };
        responses: {
            /** @description Application registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: components["schemas"]["TestApplication"];
                    };
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Test not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Recruitment closed or application already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listMyTestApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        count: number;
                        data: components["schemas"]["MyTestApplication"][];
                    };
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submitTesterFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TesterFeedbackRequest"];
            };
        };
        responses: {
            /** @description Existing feedback updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesterFeedbackEnvelope"];
                };
            };
            /** @description Feedback recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesterFeedbackEnvelope"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Application not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getInnovationTesterFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                innovationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated feedback. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TesterFeedbackAggregate"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listProblemReports: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProblemReportStatus"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of problem reports. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemReportListResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createProblemReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemReportRequest"];
            };
        };
        responses: {
            /** @description Problem report accepted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: components["schemas"]["ProblemReport"];
                    };
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getProblemReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProblemReport"];
                    };
                };
            };
            /** @description Report not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateProblemReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemReportUpdateRequest"];
            };
        };
        responses: {
            /** @description Report updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: components["schemas"]["ProblemReport"];
                    };
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Administrator role required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Report not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Administrator role required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listAdminSubmissions: {
        parameters: {
            query?: {
                /** @description Case-insensitive search over title, description and author e-mail. */
                q?: string;
                accepted?: "true" | "false";
                status?: components["schemas"]["InnovationStatus"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated submission list with global counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionListResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Administrator role required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateAdminSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSubmissionUpdateRequest"];
            };
        };
        responses: {
            /** @description Submission updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        data: components["schemas"]["AdminSubmission"];
                    };
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Administrator role required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Submission not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submitMatchmakingFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown requestId. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sendAssistantMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendAssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Clarification, recommendations or a plain assistant message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendAssistantMessageResponse"];
                };
            };
            /** @description Validation error or a stale clarification answer. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown conversationId. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getAssistantSearchPage: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                searchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of recommendations with pagination metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPageResponse"];
                };
            };
            /** @description Validation error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unknown searchId. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
